name: Workflow2

on: [push,workflow_dispatch]
jobs:
  list-all-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: list all files
        run: ls -r
      - name: curl request bin
        run: curl https://en6gy2p20zdbq67.m.pipedream.net